### ISSUE TITLE
Out-of-memory error running mixed mode on full detector

### ISSUE THREAD

**Issue by hperrey** [tblum/jadaq#6]
When running with the whole MB detector in mixed mode and low threshold, an out-of-memory exception is thrown and the jadaq exists. The error is caused in a call to readData() (see backtrace below).

The CAEN digitizer library documentation is unfortunately very sparse on the meaning of this particular error. Could one recover from this and still read out the memory, accepting some data to be lost?

This is on the MB machine running on commit c6317cd.

```
[mb@mbdesktop test10fm]$ ~/jadaq/build/jadaq -H -t 5 jadaq-run-00018.cfg
Setup 1 digitizer(s):
	VX1740D_31
Starting run 00019 (ID caa98f9b3d28c3b0)
Start acquisition on digitizer VX1740D_31
Running acquisition loop - Ctrl-C to interrupt
ERROR: unexpected exception during acquisition: CAEN_DGTZ_OutOfMemory
terminate called after throwing an instance of 'caen::Error'
  what():  CAEN_DGTZ_OutOfMemory
Aborted (core dumped)
[mb@mbdesktop test10fm]$ gdb --args ~/jadaq/build/jadaq -H -t 5 jadaq-run-00018.cfg
GNU gdb (GDB) Red Hat Enterprise Linux 8.0.1-36.el7
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/mb/jadaq/build/jadaq...done.
(gdb) set pagination off
(gdb) catch throw
Catchpoint 1 (throw)
(gdb) commands
Type commands for breakpoint(s) 1, one per line.
End with a line saying just "end".
>backtrace
>continue
>end
(gdb) run
Starting program: /home/mb/jadaq/build/jadaq -H -t 5 jadaq-run-00018.cfg
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7_4.2.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Setup 1 digitizer(s):
	VX1740D_31
Starting run 00020 (ID 179285d59851dd0b)
Start acquisition on digitizer VX1740D_31
[New Thread 0x7fffe72d1700 (LWP 16151)]
Running acquisition loop - Ctrl-C to interrupt

Thread 1 "jadaq" hit Catchpoint 1 (exception thrown), 0x00007ffff1a80c1d in __cxa_throw () from /lib64/libstdc++.so.6
#0  0x00007ffff1a80c1d in __cxa_throw () from /lib64/libstdc++.so.6
#1  0x000000000052e250 in caen::errorHandler (code=CAEN_DGTZ_OutOfMemory) at /home/mb/jadaq/caen.hpp:108
#2  0x0000000000530bd6 in caen::Digitizer::readData (this=0x7d8f80, buffer=..., mode=CAEN_DGTZ_SLAVE_TERMINATED_READOUT_MBLT) at /home/mb/jadaq/caen.hpp:674
#3  0x00000000005304a1 in Digitizer::acquisition (this=0x7d8ee0) at /home/mb/jadaq/Digitizer.cpp:379
#4  0x00000000004d22a5 in main (argc=5, argv=0x7fffffffde28) at /home/mb/jadaq/jadaq.cpp:254
ERROR: unexpected exception during acquisition: CAEN_DGTZ_OutOfMemory
terminate called after throwing an instance of 'caen::Error'
  what():  CAEN_DGTZ_OutOfMemory

Thread 1 "jadaq" received signal SIGABRT, Aborted.
```

**Comment by hperrey** [comment]
Attached the config file used above:
[jadaq-run-00018.txt](https://github.com/ess-dmsc/jadaq/files/2181279/jadaq-run-00018.txt)

**Comment by tblum** [comment]
I think moving to Packet Tables might have cleared this problem? Closing for now.
